//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2C2P.CustomerInquiry.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public decimal id { get; set; }
        public decimal customerid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string currencycode { get; set; }
        public Nullable<short> status { get; set; }
    }
}
